### ISSUE TITLE
GACD does not launch

### ISSUE THREAD

**Issue by Manos654764** [oxiox24/GetACleanerDesktop#1]
what should happen:
double-click GACD
GACD opens

what happens:
double-click GACD
does not open

it says it cant find its icon
take a look:

Traceback (most recent call last):
  File "v2.py", line 35, in <module>
  File "customtkinter\windows\ctk_tk.py", line 232, in iconbitmap
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "assets/gacd.ico" not defined

**Comment by SlowOnARocket** [comment]
Sorry didnt notice this well that's embarassing. donwload this and extract it into the same directory as the .exe I'll
 upload a fix later today [assets.zip](https://github.com/oxiox24/GetACleanerDesktop/files/14045096/assets.zip)
sorry for the really late anwser
